# Generated by Django 3.2 on 2024-08-15 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNewsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(help_text='Email name.', max_length=100, unique=True, verbose_name='Email name')),
                ('content', models.TextField(help_text='Content.', max_length=1500, verbose_name='Content')),
                ('code', models.CharField(blank=True, help_text='Code.', max_length=100, null=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Email news notification',
                'verbose_name_plural': 'Email news notifications',
            },
        ),
        migrations.CreateModel(
            name='StockEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(help_text='Requested quantity.', verbose_name='Requested quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('answer_sent', models.BooleanField(default=False, help_text='Answer send.', verbose_name='Answer send')),
                ('requested_attributes_values', models.ManyToManyField(help_text='Requested attributes values.', related_name='email_attributes_values', to='inventory.ProductAttributeValue', verbose_name='Requested attributes values')),
                ('requested_product', models.ForeignKey(help_text='Requested product.', on_delete=django.db.models.deletion.CASCADE, related_name='email_product', to='inventory.product', verbose_name='Requested product')),
                ('user', models.ForeignKey(help_text='Requested user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requested user')),
            ],
            options={
                'verbose_name': 'Stock email notification',
                'verbose_name_plural': 'Stock email notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
