# Generated by Django 3.2 on 2024-08-15 05:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length=50, unique=True, blank=False', max_length=50, unique=True, verbose_name='Role name')),
                ('description', models.TextField(blank=True, help_text='format: not required, max_length=500', max_length=500, null=True, verbose_name='Role description')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='Last name')),
                ('birthday', models.DateField(blank=True, help_text='format: not required', null=True, verbose_name='Birthday')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('subscription', models.BooleanField(default=False, help_text='format: not required', verbose_name='Subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('role', models.ForeignKey(help_text='format: not required', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.role', verbose_name='Role')),
                ('user', models.OneToOneField(help_text='format: required, unique=True', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='Country')),
                ('county_region', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='County/region')),
                ('city', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='City')),
                ('address_line', models.CharField(help_text='format: required, max_length=150', max_length=150, verbose_name='Address line')),
                ('zip_code', models.CharField(help_text='format: required, max_length=10', max_length=10, verbose_name='Zip code')),
                ('phone_number', models.CharField(help_text='format: required, max_length=15', max_length=15, verbose_name='Phone')),
                ('is_primary', models.BooleanField(default=False, help_text='format: not required', verbose_name='Is primary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
