# Generated by Django 3.2 on 2024-08-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=1, help_text='format: not required', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.role', verbose_name='Role'),
        ),
    ]
