# Generated by Django 3.2 on 2024-08-15 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Categories'),
            preserve_default=False,
        ),
    ]
